#!/usr/bin/env php
<?php
/**
 * Fecshop console bootstrap file.
 * @link http://www.fecshop.com/
 * @copyright Copyright (c) 2016 Fecshop Software LLC
 * @license http://www.fecshop.com/license/
 */
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/fancyecommerce/fecshop/yii/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.php'),
    require(__DIR__ . '/common/config/main-local.php'),
    require(__DIR__ . '/console/config/main.php'),
    require(__DIR__ . '/console/config/main-local.php'),
	# fecshop services config
	require(__DIR__ . '/vendor/fancyecommerce/fecshop/config/fecshop.php'),
	# fecshop module config
	require(__DIR__ . '/vendor/fancyecommerce/fecshop/app/console/config/console.php'),
	
	# thrid part confing
	
	# common modules and services.
	require(__DIR__ . '/common/config/fecshop_local.php'),
	 
	# console local modules and services.
	require(__DIR__ . '/console/config/fecshop_local.php')
    
);

new fecshop\services\Application($config['services']);
unset($config['services']);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);